# Generated by Django 5.2.3 on 2025-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_new_number_of_gift_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='show_in_api',
            field=models.BooleanField(default=False),
        ),
    ]
